### ISSUE TITLE
TCR loss

### ISSUE THREAD

**Issue by thomascong121** [aamir-mustafa/Transformation-CR#2]
Hi @aamir-mustafa, thank you for the great work. I have an issue applying your code, I notice that you apply TCR loss on both labeled and unlabelled data, 

 L = Ls(x, y) + λLus(u) + Lus(x)

but in your code, it seems like you have only applied TCR loss on the unlabelled data
`
loss_ours= criterion(model(transformed_input), tcr(model(input_un),random))
`

**Comment by aamir-mustafa** [comment]
Hi,
Thanks for your interest in our work.
Yes in the current implementation on github, TCR has been applied only on the unsupervised data. However, in the actual work it has to be applied on both the datasets. Further, you need to loop over the unlabelled data to generate different random samples from the same batch (i.e apply TCR in loops- not only once per batch).
Right now this has been intentionally done so that people can easily implement it, because otherwise most of the GPUs run out of memory.
Hope that helps

**Comment by thomascong121** [comment]
Thanks for the reply, what does it mean by applying TCR in loops? Do you mean we need to apply TCR separately on each unlabelled data of the same batch? Moreover, I assume the model in this implementation is also a lightweight one, have you used a more complicated model in the actual implementation?
